name: "secrets"
version: "3.2.2"
usage: "Encrypts secret values to store them in a GIT repo"
description: |-
  This plugin provides secrets values encryption for Helm charts to store them securely in GIT repos
command: "$HELM_PLUGIN_DIR/secrets.py"
hooks:
  install: "$HELM_PLUGIN_DIR/install.sh"
  update: "$HELM_PLUGIN_DIR/install.sh"
